name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-runner:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-runner.outputs.label }}
    steps:
      - id: create-runner
        uses: related-sciences/gce-github-runner@main
        with:
          token: ${{ secrets.GH_SA_TOKEN }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          runner_service_account: ${{ secrets.GCP_RUNNER_SA_EMAIL }}
          image_project: "ml-images"
          image: c0-deeplearning-common-cu124-v20241224-debian-11-py310
          machine_zone: "us-central1-a"
          machine_type: "g2-standard-4"
          disk_size: "200"
          accelerator: "count=1,type=nvidia-l4"

  test:
    needs: create-runner
    runs-on: ${{ needs.create-runner.outputs.label }}
    steps:
      - name: install CUDA drivers
        run: |
          sudo /opt/deeplearning/install-driver.sh

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: run
        run: |
          uv run python test.py
