name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-runner:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-runner.outputs.label }}
    steps:
      - id: create-runner
        uses: related-sciences/gce-github-runner@main
        with:
          token: ${{ secrets.GH_SA_TOKEN }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          runner_service_account: ${{ secrets.GCP_RUNNER_SA_EMAIL }}
          image_project: "ml-images"
          image: "c2-deeplearning-pytorch-2-4-cu124-v20241224-debian-11"
          machine_zone: "us-central1-a"
          machine_type: "g2-standard-4"
          disk_size: "100"
          accelerator: "count=1,type=nvidia-l4"

  test:
    needs: create-runner
    runs-on: ${{ needs.create-runner.outputs.label }}
    steps:
      - name: install CUDA drivers
        run: |
          if test -f /opt/google/cuda-installer
          then
            exit
          fi

          mkdir -p /opt/google/cuda-installer/
          cd /opt/google/cuda-installer/ || exit

          curl -fSsL -O https://github.com/GoogleCloudPlatform/compute-gpu-installation/releases/download/cuda-installer-v1.2.0/cuda_installer.pyz
          python3 cuda_installer.pyz install_cuda

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: run
        run: |
          uv run python test.py
